# Generated by Django 6.0.8 on 2026-08-14 14:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Đã tải lên'), ('PREVIEWED', 'Đã xem trước'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Thất bại')], db_index=True, default='UPLOADED', max_length=20)),
                ('mapping_snapshot', models.JSONField(blank=True, default=dict)),
                ('duplicate_action', models.CharField(choices=[('SKIP', 'Bỏ qua'), ('UPDATE', 'Cập nhật')], default='SKIP', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TIKTOK', 'TikTok'), ('SHOPEE', 'Shopee'), ('FACEBOOK', 'Facebook'), ('ZALO', 'Zalo'), ('OTHER', 'Khác')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=255)),
                ('default_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['internal_sku'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_order_id', models.CharField(max_length=160)),
                ('platform_user_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('shipping_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('order_created_at', models.DateTimeField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('source_type', models.CharField(default='IMPORT', max_length=20)),
                ('data_quality_status', models.CharField(choices=[('GOOD', 'Tốt'), ('WARNING', 'Cảnh báo'), ('ERROR', 'Lỗi')], db_index=True, default='GOOD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.importbatch')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.platform')),
            ],
            options={
                'ordering': ['-order_created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('seller_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('platform_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('affiliate_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('cost_of_goods', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('shipping_cost_seller', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('other_variable_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('allocated_ad_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('contribution_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='MappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_profiles', to='core.platform')),
            ],
            options={
                'ordering': ['platform', 'name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='core.platform'),
        ),
        migrations.CreateModel(
            name='PlatformCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(max_length=160)),
                ('internal_customer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.platform')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.platformcustomer'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(blank=True, max_length=160)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('external_sku', models.CharField(blank=True, db_index=True, max_length=160)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('variant_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('original_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('seller_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('platform_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('gross_item_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.product')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sku', models.CharField(blank=True, max_length=160)),
                ('external_product_name', models.CharField(blank=True, max_length=255)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=5)),
                ('mapping_source', models.CharField(choices=[('MANUAL', 'Thủ công'), ('IMPORT', 'Import'), ('AI_CONFIRMED', 'AI đã xác nhận')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='core.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='RawOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('RAW', 'Raw'), ('VALID', 'Hợp lệ'), ('WARNING', 'Cảnh báo'), ('ERROR', 'Lỗi'), ('DUPLICATE', 'Trùng lặp'), ('COMMITTED', 'Đã ghi')], db_index=True, default='RAW', max_length=20)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('warning_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.importbatch')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('ERROR', 'Lỗi'), ('WARNING', 'Cảnh báo')], db_index=True, max_length=10)),
                ('field_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_value', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Chưa xử lý'), ('RESOLVED', 'Đã xử lý')], db_index=True, default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='core.importbatch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='core.order')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='core.raworderrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=160)),
                ('target_field', models.CharField(max_length=100)),
                ('transform_rule', models.CharField(blank=True, max_length=80)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.mappingprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'source_column'), name='uq_mapping_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='mappingprofile',
            constraint=models.UniqueConstraint(fields=('platform', 'name', 'version'), name='uq_mapping_version'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['platform', 'created_at'], name='core_import_platfor_2136b2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformcustomer',
            index=models.Index(fields=['platform', 'platform_user_id'], name='core_platfo_platfor_d651a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformcustomer',
            constraint=models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='uq_platform_customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform', 'external_order_id'], name='core_order_platfor_e1e94e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform', 'order_created_at'], name='core_order_platfor_4bab26_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('platform', 'external_order_id'), name='uq_platform_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_item_id', ''), _negated=True), fields=('order', 'external_item_id'), name='uq_order_external_item'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_item_id', '')), fields=('order', 'external_sku', 'line_number'), name='uq_order_fallback_item'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['platform', 'external_sku'], name='core_produc_platfor_cdc028_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(fields=('platform', 'external_sku', 'external_product_name'), name='uq_product_alias'),
        ),
        migrations.AddIndex(
            model_name='raworderrecord',
            index=models.Index(fields=['import_batch', 'processing_status'], name='core_raword_import__0c72ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='raworderrecord',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uq_raw_batch_row'),
        ),
        migrations.AddIndex(
            model_name='dataqualityissue',
            index=models.Index(fields=['import_batch', 'severity', 'status'], name='core_dataqu_import__6c9c0f_idx'),
        ),
    ]
